apiVersion: apps/v1
kind: Deployment
metadata:
  name: views-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: views-service
  template:
    metadata:
      labels:
        app: views-service
    spec:
      containers:
      - name: views-service-container
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: cloud-computing-secret
                key: deductive-cider-407703-sa.json
          - name: PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: cloud-computing-secret
                key: project-id.json