apiVersion: apps/v1
kind: Deployment
metadata:
  name: views-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: views-service
  template:
    metadata:
      labels:
        app: views-service
    spec:
      containers:
      - name: views-service-container
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8090