name: Build and Deploy views-service to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{secrets.CLOUD_COMPUTING_GKE_PROJECT}}
  GKE_CLUSTER: cloud-computing-cluster
  GKE_ZONE: asia-southeast1-b
  DEPLOYMENT_NAME: views-service-deployment
  IMAGE: mpansuja95/cloud-computing-views-service
  TAG: views.0.0.1

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy views-service
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.10.0'

      - name: Install Dependencies
        run: npm install  

      - name: Setup Google CLoud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.CLOUD_COMPUTING_GKE_KEY}}
          project_id: ${{secrets.CLOUD_COMPUTING_GKE_PROJECT}}

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker  

      - name: Get GKE Credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Build Docker Image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .

      - name: Publish Docker Image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"       

      # Example GKE deployment step:
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy Image to GKE cluster
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide    
